# Generated by Django 5.2.5 on 2025-08-15 21:44

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="default_country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_county",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_email",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_first_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_last_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_phone_number",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_postcode",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_street_address1",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_street_address2",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="default_town_or_city",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="county",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="street_address1",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="street_address2",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="town_or_city",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
