# Generated by Django 5.2.5 on 2025-08-17 21:13

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_userprofile_default_country_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="county",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="County"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="postcode",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postcode"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="street_address1",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Street address 1"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="street_address2",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="Street address 2"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="town_or_city",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Town or city"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
